// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"time"

	enums "github.com/serjnester/weather-subscription-service/domain/enums"
)

type Subscription struct {
	ID        int32
	Email     string
	City      string
	Frequency enums.Frequency
	Confirmed bool
	Token     string
	CreatedAt time.Time
}
